server:
  port: ${SERVER_PORT}

spring:
  application:
    name:myrealpet_qna

  datasource:
    url: jdbc:mysql://localhost:3306/myrealpet_qna?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    dialect: ${SPRING_DATASOURCE_DIALECT}

  jpa:
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
        jdbc:
          time_zone: Asia/Seoul   # 한국 시간 기준
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW}
    database: ${SPRING_JPA_DATABASE}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    generate-ddl: ${SPRING_JPA_GENERATE_DDL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}

cors:
  allow:
    origins: ${CORS_ALLOWED_ORIGINS}
